print("YO")
print("Update")
print("Another update")
print("One more")
print("Testing staleness")
print("Testing staleness again")
print("Stale test 3")
print("t4")
print("5")
print('6')
print('7')
print('8')
print('9')
