name: Haystack Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: haystackeditor/haystack-pr-action@v1.0.1
