name: PR Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: haystackeditor/haystack-pr-action@v1.0.0
        with:
          # Any configurable options from your website
          api_url: https://8z9ssbamdj.execute-api.us-west-2.amazonaws.com/prod